# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dc_req.proto',
  package='dc',
  serialized_pb='\n\x0c\x64\x63_req.proto\x12\x02\x64\x63\"\xb3\x02\n\x07request\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x11\n\tfrom_type\x18\x02 \x01(\x05\x12\x11\n\tis_relive\x18\x03 \x01(\x08\x12\x0f\n\x07is_asyn\x18\x04 \x01(\x08\x12\x0f\n\x07no_resp\x18\x05 \x01(\x08\x12+\n\x0b\x63heck_level\x18\x06 \x01(\x0e\x32\x0e.dc.CheckLevel:\x06NORMAL\x12&\n\rcheck_methods\x18\x07 \x03(\x0e\x32\x0f.dc.CheckMethod\x12\x12\n\ntarget_url\x18\x08 \x01(\t\x12\x0f\n\x07\x63ur_url\x18\t \x01(\t\x12\x11\n\thttp_code\x18\n \x01(\x05\x12\x0f\n\x07headers\x18\x0b \x01(\t\x12\x0c\n\x04\x62ody\x18\x0c \x01(\x0c\x12\x11\n\tresp_dest\x18\r \x01(\t\x12\x11\n\tuser_data\x18\x0e \x01(\x0c\"\xce\x01\n\x08response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06req_id\x18\x03 \x01(\x03\x12\x0f\n\x07is_asyn\x18\x04 \x01(\x08\x12\x12\n\ntarget_url\x18\x05 \x01(\t\x12\x0f\n\x07\x63ur_url\x18\x06 \x01(\t\x12\x10\n\x08next_url\x18\x07 \x01(\t\x12)\n\x0bhttp_method\x18\x08 \x01(\x0e\x32\x0f.dc.HTTP_Method:\x03GET\x12\x11\n\tresp_dest\x18\t \x01(\t\x12\x11\n\tuser_data\x18\n \x01(\x0c*6\n\x0b\x43heckMethod\x12\x08\n\x04HTTP\x10\x00\x12\x08\n\x04LINK\x10\x01\x12\t\n\x05TITLE\x10\x02\x12\x08\n\x04\x42ODY\x10\x03*+\n\nCheckLevel\x12\x07\n\x03LOW\x10\x05\x12\n\n\x06NORMAL\x10\n\x12\x08\n\x04HIGH\x10\x0f**\n\x0bHTTP_Method\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04HEAD\x10\x01\x12\x08\n\x04POST\x10\x02')

_CHECKMETHOD = descriptor.EnumDescriptor(
  name='CheckMethod',
  full_name='dc.CheckMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='HTTP', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LINK', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TITLE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BODY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=539,
  serialized_end=593,
)


_CHECKLEVEL = descriptor.EnumDescriptor(
  name='CheckLevel',
  full_name='dc.CheckLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NORMAL', index=1, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=595,
  serialized_end=638,
)


_HTTP_METHOD = descriptor.EnumDescriptor(
  name='HTTP_Method',
  full_name='dc.HTTP_Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEAD', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POST', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=640,
  serialized_end=682,
)


HTTP = 0
LINK = 1
TITLE = 2
BODY = 3
LOW = 5
NORMAL = 10
HIGH = 15
GET = 0
HEAD = 1
POST = 2



_REQUEST = descriptor.Descriptor(
  name='request',
  full_name='dc.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='req_id', full_name='dc.request.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='from_type', full_name='dc.request.from_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_relive', full_name='dc.request.is_relive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_asyn', full_name='dc.request.is_asyn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='no_resp', full_name='dc.request.no_resp', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='check_level', full_name='dc.request.check_level', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='check_methods', full_name='dc.request.check_methods', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_url', full_name='dc.request.target_url', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cur_url', full_name='dc.request.cur_url', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='http_code', full_name='dc.request.http_code', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headers', full_name='dc.request.headers', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='dc.request.body', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resp_dest', full_name='dc.request.resp_dest', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_data', full_name='dc.request.user_data', index=13,
      number=14, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=328,
)


_RESPONSE = descriptor.Descriptor(
  name='response',
  full_name='dc.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='dc.response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg', full_name='dc.response.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='req_id', full_name='dc.response.req_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_asyn', full_name='dc.response.is_asyn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_url', full_name='dc.response.target_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cur_url', full_name='dc.response.cur_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='next_url', full_name='dc.response.next_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='http_method', full_name='dc.response.http_method', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resp_dest', full_name='dc.response.resp_dest', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_data', full_name='dc.response.user_data', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=537,
)

_REQUEST.fields_by_name['check_level'].enum_type = _CHECKLEVEL
_REQUEST.fields_by_name['check_methods'].enum_type = _CHECKMETHOD
_RESPONSE.fields_by_name['http_method'].enum_type = _HTTP_METHOD
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE

class request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:dc.request)

class response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:dc.response)

# @@protoc_insertion_point(module_scope)
